### PR TITLE
Allow a failed cradle to report diagnostics and implement none cradle

### LINKED ISSUE #8: Improve ghc session error handling
* If cradle run is succesful but ghc session crashes the ide does not get any error and progress gets stuck
* The workaround is extract compiler args and call ghc directly on command line to see what is going on
* Detected when opening ghc with hls on windows but i think the behaviour is similar with other projects

### PR DESCRIPTION
**Pull request by mpickering**
The rendering of the error could be better but it's still a good
improvement.

@jneira Can you test this please?

Fixes #8

### CODE REVIEW

**Comment by jneira** [comment]
@mpickering sure, i will test with, for example, `hadrian/hie-bios.bat` asap

**Comment by mpickering** [comment]
Rebased now.

**Comment by jneira** [comment]
I've tested it without success. My steps has been:
* Install this ghcide version
* Check ghcide starts the ghc session in the project ghc with the actual `hie-bios.bat`
* Change `hadrian/hie-bios.bat` to output a bad argument:
```
set TERM=dumb
set CABFLAGS=-v0
echo --badarg > %HIE_BIOS_OUTPUT%
```
* Open `compiler/GHC.hs`
* The output is like when i had ghc session errors before:
```
[client] run command = "ghcide --lsp"
[client] debug command = "ghcide --lsp"
ghcide version: 0.1.0 (GHC: 8.8.3) (PATH: D:\bin\ghcide.exe) (GIT hash: )
Starting LSP server...
If you are seeing this in a terminal, you probably should have run ghcide WITHOUT the --lsp option!
 Started LSP server in 0.11s
[INFO] Opened text document: file:///d%3A/dev/ws/haskell/ghc/compiler/GHC.hs
Consulting the cradle for "D:\\dev\\ws\\haskell\\ghc\\compiler\\GHC.hs"
> 
> D:\dev\ws\haskell\ghc>set TERM=dumb 
> 
> D:\dev\ws\haskell\ghc>set CABFLAGS=-v0 
> 
> D:\dev\ws\haskell\ghc>echo --badarg  1>C:\TEMP\hie3631 
Right (ComponentOptions {componentOptions = ["--badarg"], componentRoot = "D:\\dev\\ws\\haskell\\ghc", componentDependencies = []})
```

There is no more output and the progress get stuck.

**Comment by mpickering** [comment]
I think the `--badarg` will just be ignored. I didn't anticipate your use case but you can trigger the failure if the cradle itself fails to build for some reason. In your case the cradle returned succesfully and a session was started which contained no arguments.

**Comment by jneira** [comment]
Mmm, [my issue ](https://github.com/mpickering/ghcide/issues/8) was motivated by a similar case i've reproduced: bad ghc arguments, like `-I.hie-bios/whatever` that made the ghc call fail (i thought that ghc session failed by the same cause). 

In those cases the cradle was succesful and the component options presented but i could not see the `(([],Just HscEnvEq 2),fromList [])`, the log got stuck after showing component options, like my test with `--badarg`.

Testing with hie-bios gives me this output:
```
PS D:\dev\ws\haskell\ghc> hie-bios debug .\compiler\GHC.hs
Root directory:      D:\dev\ws\haskell\ghc
Component directory: D:\dev\ws\haskell\ghc
GHC options:         "--badarg "
System libraries:    D:\bin\stack\x86_64-windows\ghc-8.8.3\lib
Config Location:     D:\dev\ws\haskell\ghc\hie.yaml
Cradle:              Cradle {cradleRootDir = "D:\\dev\\ws\\haskell\\ghc", cradleOptsProg = CradleAction: Bios}
Dependencies:
PS D:\dev\ws\haskell\ghc> hie-bios check .\compiler\GHC.hs
hie-bios.exe: target â€˜--badarg â€™ is not a module name or a source file
```
Otoh if i change `--badarg` with a valid argument like `-v` the ghc session is started:

```
[client] run command = "ghcide --lsp"
[client] debug command = "ghcide --lsp"
ghcide version: 0.1.0 (GHC: 8.8.3) (PATH: D:\bin\ghcide.exe) (GIT hash: )
Starting LSP server...
If you are seeing this in a terminal, you probably should have run ghcide WITHOUT the --lsp option!
 Started LSP server in 0.02s
[INFO] Opened text document: file:///d%3A/dev/ws/haskell/ghc/compiler/GHC.hs
Consulting the cradle for "D:\\dev\\ws\\haskell\\ghc\\compiler\\GHC.hs"
> 
> D:\dev\ws\haskell\ghc>set TERM=dumb 
> 
> D:\dev\ws\haskell\ghc>set CABFLAGS=-v0 
> 
> D:\dev\ws\haskell\ghc>echo -v  1>C:\TEMP\hie8404 
Right (ComponentOptions {componentOptions = ["-v "], componentRoot = "D:\\dev\\ws\\haskell\\ghc", componentDependencies = []})
Using binary package database: D:\\bin\stack\x86_64-windows\ghc-8.8.3\lib\package.conf.d\package.cache
There is no package.cache in C:\Users\atrey\AppData\Roaming\ghc\x86_64-mingw32-8.8.3\package.conf.d, checking if the database is empty
There are no .conf files in C:\Users\atrey\AppData\Roaming\ghc\x86_64-mingw32-8.8.3\package.conf.d, treating package database as empty
package flags []
loading package database D:\\bin\stack\x86_64-windows\ghc-8.8.3\lib\package.conf.d
loading package database C:\Users\atrey\AppData\Roaming\ghc\x86_64-mingw32-8.8.3\package.conf.d
wired-in package ghc-prim mapped to ghc-prim-0.5.3
wired-in package integer-wired-in mapped to integer-gmp-1.0.2.0
wired-in package base mapped to base-4.13.0.0
wired-in package rts mapped to rts
wired-in package template-haskell mapped to template-haskell-2.15.0.0
wired-in package ghc mapped to ghc-8.8.3
"Making new HscEnv[main]"
package flags []
loading package database D:\\bin\stack\x86_64-windows\ghc-8.8.3\lib\package.conf.d
loading package database C:\Users\atrey\AppData\Roaming\ghc\x86_64-mingw32-8.8.3\package.conf.d
wired-in package ghc-prim mapped to ghc-prim-0.5.3
wired-in package integer-wired-in mapped to integer-gmp-1.0.2.0
wired-in package base mapped to base-4.13.0.0
wired-in package rts mapped to rts-1.0
wired-in package template-haskell mapped to template-haskell-2.15.0.0
wired-in package ghc mapped to ghc-8.8.3
Error while checking GHC version: "D:\\\\bin\\\\stack\\\\x86_64-windows\\\\ghc-8.8.3\\\\lib\\bin\\ghc: readCreateProcess: does not exist (No such file or directory)"
(([],Just HscEnvEq 2),fromList [])
*** Deleting temp files:
Deleting: C:\TEMP\ghc15640_0\ghc_1.h
*** Deleting temp dirs:
Deleting: C:\TEMP\ghc15640_0
*** Deleting temp files:
Deleting: C:\TEMP\ghc15640_2\ghc_3.h
*** Deleting temp dirs:
Deleting: C:\TEMP\ghc15640_2
[INFO] finish: CodeAction (took 0.07s)
[INFO] finish: InitialLoad (took 0.14s)
[INFO] finish: CodeAction (took 0.03s)
[INFO] finish: CodeAction:PackageExports (took 38.98s)
[INFO] finish: CodeAction:PackageExports (took 0.00s)
```
Then i see a looot of errors in the problems tabs about missing modules (as expected).

Note in the output that i am getting another error i did not see before:

```
Error while checking GHC version: "D:\\\\bin\\\\stack\\\\x86_64-windows\\\\ghc-8.8.3\\\\lib\\bin\\ghc: readCreateProcess: does not exist (No such file or directory)"
```
but i got that one with the original `hie-bios.bat`

**Comment by mpickering** [comment]
> Error while checking GHC version: "D:\\\\bin\\\\stack\\\\x86_64-windows\\\\ghc-8.8.3\\\\lib\\bin\\ghc: readCreateProcess: does not exist (No such file or directory)"

That is an upstream issue. I will comment out the check on our branch until it is fixed.

**Comment by mpickering** [comment]
I will test the situation you are describing. I think this patch is still an improvement though?

**Comment by jneira** [comment]
yeah, absolutly, i changed the test case to make `hie-bios.bat` fail instead return bad arguments and i see the error in vscode:

* hie-bios.bat:
```
set TERM=dumb
set CABFLAGS=-v0
echoes -v > %HIE_BIOS_OUTPUT%
```
* output:
```
[client] run command = "ghcide --lsp"
[client] debug command = "ghcide --lsp"
ghcide version: 0.1.0 (GHC: 8.8.3) (PATH: D:\bin\ghcide.exe) (GIT hash: )
Starting LSP server...
If you are seeing this in a terminal, you probably should have run ghcide WITHOUT the --lsp option!
 Started LSP server in 0.05s
[INFO] Opened text document: file:///d%3A/dev/ws/haskell/ghc/compiler/GHC.hs
Consulting the cradle for "D:\\dev\\ws\\haskell\\ghc\\compiler\\GHC.hs"
> 
> D:\dev\ws\haskell\ghc>set TERM=dumb 
> 
> D:\dev\ws\haskell\ghc>set CABFLAGS=-v0 
> 
> D:\dev\ws\haskell\ghc>echoes -v  1>C:\TEMP\hieE7B5 
> "echoes" no se reconoce como un comando interno o externo,
> programa o archivo por lotes ejecutable.
Left [CradleError (ExitFailure 1) ["\"echoes\" no se reconoce como un comando interno o externo,","programa o archivo por lotes ejecutable."]]
```

And i can see the error in vscode error pane:
imagen

However the client enter in a loop consulting the cradle continuosly and repeating the above output :thinking:

The message is good but maybe is lacking some context: it seems the error is related with `GHC.hs`. Maybe an error alert would be better? With something like `Error initializing project: actual error`

**Comment by mpickering** [comment]
I fixed the loop on my latest push. 

I am not sure how to trigger an error alert from ghcide!

**Pull request merged**
